using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ApplyResourcesSourceGen
{
    [Generator]
    public class Generator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var applyResourcesLocations = context.SyntaxProvider
                .CreateSyntaxProvider(predicate: (node, _) => node is InvocationExpressionSyntax, transform: SyntaxProviderLocationTransformer)
                .Where(x => x is not null)
                .Collect();

            context.RegisterSourceOutput(source: applyResourcesLocations, action: SourceOutputAction);
        }

        private static Location SyntaxProviderLocationTransformer(GeneratorSyntaxContext context, CancellationToken ct)
        {
            var invocationExpression = (InvocationExpressionSyntax)context.Node;

            var invocationSymbol = context.SemanticModel.GetSymbolInfo(invocationExpression);

            var applyResourcesMethod = context.SemanticModel.Compilation
                .GetTypeByMetadataName("System.ComponentModel.ComponentResourceManager")
                ?.GetMembers("ApplyResources")
                .OfType<IMethodSymbol>()
                .FirstOrDefault(m => m.Parameters.Length == 2);

            if (invocationSymbol.Symbol is not IMethodSymbol methodSymbol ||
                applyResourcesMethod is null ||
                !methodSymbol.Equals(applyResourcesMethod, SymbolEqualityComparer.Default))
                return null!;

            var memberAccessExpression = (MemberAccessExpressionSyntax)invocationExpression.Expression;

            return memberAccessExpression.Name.GetLocation();
        }

        private static void SourceOutputAction(SourceProductionContext context, ImmutableArray<Location> locations)
        {
            var builder = new StringBuilder();

            builder.AppendLine(
            $$"""
            // <auto-generated/>

            namespace System.Runtime.CompilerServices
            {
                [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
                file sealed class InterceptsLocationAttribute : Attribute
                {
                    public InterceptsLocationAttribute(string filePath, int line, int column)
                    {
                    }
                }
            }

            static class Intercepforms
            {
            """);

            int i = 1;
            foreach (var location in locations)
            {
                if (location.SourceTree is null)
                    continue;

                var lineSpan = location.GetLineSpan();

                builder.AppendLine("");
                builder.AppendLine($"""
                    [global::System.Runtime.CompilerServices.InterceptsLocation(@"{location.SourceTree.FilePath}", {lineSpan.StartLinePosition.Line + 1}, {lineSpan.StartLinePosition.Character + 1})]
                """);
                builder.AppendLine($"""
                    public static void ApplyResources{i}(this System.ComponentModel.ComponentResourceManager manager, object value, string objectName)
                    {"{"}
                        System.Diagnostics.Debug.WriteLine("ApplyResources{i}");
                        manager.ApplyResources(value, objectName);
                    {"}"}
                """);

                i++;
            }

            builder.AppendLine(
            $$"""
            }
            """);

            context.AddSource("ApplyResources.g.cs", builder.ToString());
        }
    }
}

